import { fileURLToPath } from "node:url";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    tsconfigPaths: true,
    alias: {
      "server-only": fileURLToPath(new URL("./test/stubs/server-only.ts", import.meta.url)),
    },
  },
  test: {
    globals: true,
    exclude: ["**/node_modules/**", "**/dist/**", "e2e/**"],
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "lcov"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.test.{ts,tsx}",
        // Generated by the shadcn CLI, owned upstream.
        "src/components/ui/**",
        // Barrels are re-exports with no behaviour to cover.
        "src/**/index.ts",
        // Route entry points and boundaries: markup wired to the Next runtime.
        // Exercised for real by e2e/notes.spec.ts, which asserts the rendered
        // 404, the redirect chain, and the response headers.
        "src/app/**/{page,layout,loading,error,global-error,not-found}.tsx",
        "src/app/**/{robots,sitemap}.ts",
        // Server Actions cannot be dispatched outside a Next request; the
        // sign-in and sign-out flows are covered end to end instead.
        "src/features/auth/server/auth-actions.ts",
        "src/features/auth/components/sign-out-button.tsx",
        // A pass-through around next-themes' provider.
        "src/components/theme-provider.tsx",
      ],
      // Set just under the current numbers: a ratchet, not an aspiration.
      thresholds: {
        lines: 95,
        functions: 100,
        branches: 90,
        statements: 95,
      },
    },
    env: {
      SESSION_SECRET: "test-session-secret-at-least-32-characters",
      AUTH_DEMO_EMAIL: "demo@example.com",
      AUTH_DEMO_PASSWORD: "demo-password",
      NEXT_PUBLIC_APP_URL: "http://localhost:3000",
    },
    // Extension picks the environment: `.test.ts` is server code and runs in
    // node, `.test.tsx` renders components and runs in jsdom. Server modules
    // must not see a `window` — @t3-oss/env-nextjs uses it to decide whether
    // server variables are readable.
    projects: [
      {
        extends: true,
        test: {
          name: "server",
          environment: "node",
          include: ["src/**/*.test.ts"],
        },
      },
      {
        extends: true,
        test: {
          name: "browser",
          environment: "jsdom",
          include: ["src/**/*.test.tsx"],
          setupFiles: ["./vitest.setup.ts"],
        },
      },
    ],
  },
});
